on:
  push:
    branches: [master]

jobs:
  hello_world_job:
    runs-on: [self-hosted, test]
    name: Run docker commands in github runners
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker build
        run: |
           docker build -t test-image .
#          docker run --tmpfs /build:exec --rm -v $(pwd)/tmp:/tmp test-image
