# This is a test workflow to trigger Alpa CI
name: Trigger Alpa Build workflow

on:
  workflow_dispatch:
    inputs:
      alpa-branch-name:
        description: 'Alpa branch to test'
        required: true
        default: 'main'
      
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "TensorFlow Alpa branch: ${TF_BRANCH##*/}"
          echo "Alpa branch: $ALPA_BRANCH"
        env:
          TF_BRANCH: ${{github.ref}}
          ALPA_BRANCH: ${{github.event.inputs.alpa-branch-name}}
          
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'zhisbug',
              repo: 'test-alpa-ci-runner',
              workflow_id: 'test-build-dispatch.yml',
              ref: $ALPA_BRANCH
            })
        env:
          TF_BRANCH: ${{github.ref}}
          ALPA_BRANCH: ${{github.event.inputs.alpa-branch-name}}
