# This is a test workflow to trigger Alpa CI
name: Trigger Alpa Build workflow
on:
  push: 
    branches: [ master ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'alpa-projects',
            repo: 'alpa',
            workflow_id: 'main.yml',
            ref: 'hao-wheel-2'
          })
